# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Cart.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nCart.proto\"-\n\x06Pedido\x12\x10\n\x08pedidoId\x18\x01 \x01(\x05\x12\x11\n\tproductId\x18\x02 \x01(\x05\"\x1c\n\x08PedidoId\x12\x10\n\x08pedidoId\x18\x01 \x01(\x05\"\x1f\n\nProductoId\x12\x11\n\tproductId\x18\x01 \x01(\x05\"\x06\n\x04Nada\"0\n\x08Response\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc9\x01\n\x04\x43\x61rt\x12!\n\tAddToCart\x12\x07.Pedido\x1a\t.Response\"\x00\x12(\n\x0eRemoveFromCart\x12\t.PedidoId\x1a\t.Response\"\x00\x12\x1e\n\x08ViewCart\x12\x05.Nada\x1a\t.Response\"\x00\x12-\n\x11ViewProductInCart\x12\x0b.ProductoId\x1a\t.Response\"\x00\x12%\n\x0b\x41\x64\x64Quantity\x12\t.PedidoId\x1a\t.Response\"\x00\x42\x13\x42\tCartProtoP\x01\xa2\x02\x03\x43rPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Cart_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\tCartProtoP\001\242\002\003CrP'
  _PEDIDO._serialized_start=14
  _PEDIDO._serialized_end=59
  _PEDIDOID._serialized_start=61
  _PEDIDOID._serialized_end=89
  _PRODUCTOID._serialized_start=91
  _PRODUCTOID._serialized_end=122
  _NADA._serialized_start=124
  _NADA._serialized_end=130
  _RESPONSE._serialized_start=132
  _RESPONSE._serialized_end=180
  _CART._serialized_start=183
  _CART._serialized_end=384
# @@protoc_insertion_point(module_scope)
