// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: helloworld/Cart.proto

package helloworld

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PedidoId  int32 `protobuf:"varint,1,opt,name=pedidoId,proto3" json:"pedidoId,omitempty"`
	ProductId int32 `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
}

func (x *Pedido) Reset() {
	*x = Pedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_Cart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pedido) ProtoMessage() {}

func (x *Pedido) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_Cart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pedido.ProtoReflect.Descriptor instead.
func (*Pedido) Descriptor() ([]byte, []int) {
	return file_helloworld_Cart_proto_rawDescGZIP(), []int{0}
}

func (x *Pedido) GetPedidoId() int32 {
	if x != nil {
		return x.PedidoId
	}
	return 0
}

func (x *Pedido) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type Length struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length int32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *Length) Reset() {
	*x = Length{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_Cart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Length) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Length) ProtoMessage() {}

func (x *Length) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_Cart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Length.ProtoReflect.Descriptor instead.
func (*Length) Descriptor() ([]byte, []int) {
	return file_helloworld_Cart_proto_rawDescGZIP(), []int{1}
}

func (x *Length) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type PedidoId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PedidoId int32 `protobuf:"varint,1,opt,name=pedidoId,proto3" json:"pedidoId,omitempty"`
}

func (x *PedidoId) Reset() {
	*x = PedidoId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_Cart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PedidoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoId) ProtoMessage() {}

func (x *PedidoId) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_Cart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoId.ProtoReflect.Descriptor instead.
func (*PedidoId) Descriptor() ([]byte, []int) {
	return file_helloworld_Cart_proto_rawDescGZIP(), []int{2}
}

func (x *PedidoId) GetPedidoId() int32 {
	if x != nil {
		return x.PedidoId
	}
	return 0
}

type ProductoId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId int32 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
}

func (x *ProductoId) Reset() {
	*x = ProductoId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_Cart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductoId) ProtoMessage() {}

func (x *ProductoId) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_Cart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductoId.ProtoReflect.Descriptor instead.
func (*ProductoId) Descriptor() ([]byte, []int) {
	return file_helloworld_Cart_proto_rawDescGZIP(), []int{3}
}

func (x *ProductoId) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type Precio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Precio int32 `protobuf:"varint,1,opt,name=precio,proto3" json:"precio,omitempty"`
}

func (x *Precio) Reset() {
	*x = Precio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_Cart_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Precio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Precio) ProtoMessage() {}

func (x *Precio) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_Cart_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Precio.ProtoReflect.Descriptor instead.
func (*Precio) Descriptor() ([]byte, []int) {
	return file_helloworld_Cart_proto_rawDescGZIP(), []int{4}
}

func (x *Precio) GetPrecio() int32 {
	if x != nil {
		return x.Precio
	}
	return 0
}

type Nada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Nada) Reset() {
	*x = Nada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_Cart_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nada) ProtoMessage() {}

func (x *Nada) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_Cart_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nada.ProtoReflect.Descriptor instead.
func (*Nada) Descriptor() ([]byte, []int) {
	return file_helloworld_Cart_proto_rawDescGZIP(), []int{5}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_Cart_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_Cart_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_helloworld_Cart_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_helloworld_Cart_proto protoreflect.FileDescriptor

var file_helloworld_Cart_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x43, 0x61, 0x72,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x06, 0x50, 0x65, 0x64, 0x69, 0x64,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x4c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x26, 0x0a,
	0x08, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x6f, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49,
	0x64, 0x22, 0x20, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x63, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x65, 0x63, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x72, 0x65,
	0x63, 0x69, 0x6f, 0x22, 0x06, 0x0a, 0x04, 0x4e, 0x61, 0x64, 0x61, 0x22, 0x45, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x8e, 0x02, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x09, 0x41,
	0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x12, 0x07, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64,
	0x6f, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x28,
	0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x74,
	0x12, 0x09, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x49, 0x64, 0x1a, 0x09, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x1e, 0x0a, 0x08, 0x56, 0x69, 0x65, 0x77,
	0x43, 0x61, 0x72, 0x74, 0x12, 0x05, 0x2e, 0x4e, 0x61, 0x64, 0x61, 0x1a, 0x09, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x11, 0x56, 0x69, 0x65, 0x77,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x43, 0x61, 0x72, 0x74, 0x12, 0x0b, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x49, 0x64, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x09, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x49,
	0x64, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x20,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x05,
	0x2e, 0x4e, 0x61, 0x64, 0x61, 0x1a, 0x07, 0x2e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x00,
	0x12, 0x21, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x63, 0x69, 0x6f, 0x12, 0x09, 0x2e,
	0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x49, 0x64, 0x1a, 0x07, 0x2e, 0x50, 0x72, 0x65, 0x63, 0x69,
	0x6f, 0x22, 0x00, 0x42, 0x67, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f,
	0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_helloworld_Cart_proto_rawDescOnce sync.Once
	file_helloworld_Cart_proto_rawDescData = file_helloworld_Cart_proto_rawDesc
)

func file_helloworld_Cart_proto_rawDescGZIP() []byte {
	file_helloworld_Cart_proto_rawDescOnce.Do(func() {
		file_helloworld_Cart_proto_rawDescData = protoimpl.X.CompressGZIP(file_helloworld_Cart_proto_rawDescData)
	})
	return file_helloworld_Cart_proto_rawDescData
}

var file_helloworld_Cart_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_helloworld_Cart_proto_goTypes = []interface{}{
	(*Pedido)(nil),     // 0: Pedido
	(*Length)(nil),     // 1: Length
	(*PedidoId)(nil),   // 2: PedidoId
	(*ProductoId)(nil), // 3: ProductoId
	(*Precio)(nil),     // 4: Precio
	(*Nada)(nil),       // 5: Nada
	(*Response)(nil),   // 6: Response
}
var file_helloworld_Cart_proto_depIdxs = []int32{
	0, // 0: Cart.AddToCart:input_type -> Pedido
	2, // 1: Cart.RemoveFromCart:input_type -> PedidoId
	5, // 2: Cart.ViewCart:input_type -> Nada
	3, // 3: Cart.ViewProductInCart:input_type -> ProductoId
	2, // 4: Cart.AddQuantity:input_type -> PedidoId
	5, // 5: Cart.GetCarLength:input_type -> Nada
	2, // 6: Cart.GetPrecio:input_type -> PedidoId
	6, // 7: Cart.AddToCart:output_type -> Response
	6, // 8: Cart.RemoveFromCart:output_type -> Response
	6, // 9: Cart.ViewCart:output_type -> Response
	6, // 10: Cart.ViewProductInCart:output_type -> Response
	6, // 11: Cart.AddQuantity:output_type -> Response
	1, // 12: Cart.GetCarLength:output_type -> Length
	4, // 13: Cart.GetPrecio:output_type -> Precio
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_Cart_proto_init() }
func file_helloworld_Cart_proto_init() {
	if File_helloworld_Cart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_helloworld_Cart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_Cart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Length); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_Cart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PedidoId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_Cart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductoId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_Cart_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Precio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_Cart_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_Cart_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_helloworld_Cart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_Cart_proto_goTypes,
		DependencyIndexes: file_helloworld_Cart_proto_depIdxs,
		MessageInfos:      file_helloworld_Cart_proto_msgTypes,
	}.Build()
	File_helloworld_Cart_proto = out.File
	file_helloworld_Cart_proto_rawDesc = nil
	file_helloworld_Cart_proto_goTypes = nil
	file_helloworld_Cart_proto_depIdxs = nil
}
