# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Cart.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nCart.proto\"-\n\x06Pedido\x12\x10\n\x08pedidoId\x18\x01 \x01(\x05\x12\x11\n\tproductId\x18\x02 \x01(\x05\"\x18\n\x06Length\x12\x0e\n\x06length\x18\x01 \x01(\x05\"\x1c\n\x08PedidoId\x12\x10\n\x08pedidoId\x18\x01 \x01(\x05\"\x1f\n\nProductoId\x12\x11\n\tproductId\x18\x01 \x01(\x05\"\x18\n\x06Precio\x12\x0e\n\x06precio\x18\x01 \x01(\x05\"\x06\n\x04Nada\"0\n\x08Response\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8e\x02\n\x04\x43\x61rt\x12!\n\tAddToCart\x12\x07.Pedido\x1a\t.Response\"\x00\x12(\n\x0eRemoveFromCart\x12\t.PedidoId\x1a\t.Response\"\x00\x12\x1e\n\x08ViewCart\x12\x05.Nada\x1a\t.Response\"\x00\x12-\n\x11ViewProductInCart\x12\x0b.ProductoId\x1a\t.Response\"\x00\x12%\n\x0b\x41\x64\x64Quantity\x12\t.PedidoId\x1a\t.Response\"\x00\x12 \n\x0cGetCarLength\x12\x05.Nada\x1a\x07.Length\"\x00\x12!\n\tGetPrecio\x12\t.PedidoId\x1a\x07.Precio\"\x00\x42g\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01Z5google.golang.org/grpc/examples/helloworld/helloworldb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Cart_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001Z5google.golang.org/grpc/examples/helloworld/helloworld'
  _PEDIDO._serialized_start=14
  _PEDIDO._serialized_end=59
  _LENGTH._serialized_start=61
  _LENGTH._serialized_end=85
  _PEDIDOID._serialized_start=87
  _PEDIDOID._serialized_end=115
  _PRODUCTOID._serialized_start=117
  _PRODUCTOID._serialized_end=148
  _PRECIO._serialized_start=150
  _PRECIO._serialized_end=174
  _NADA._serialized_start=176
  _NADA._serialized_end=182
  _RESPONSE._serialized_start=184
  _RESPONSE._serialized_end=232
  _CART._serialized_start=235
  _CART._serialized_end=505
# @@protoc_insertion_point(module_scope)
