# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Cart_pb2 as Cart__pb2


class CartStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddToCart = channel.unary_unary(
                '/Cart/AddToCart',
                request_serializer=Cart__pb2.Pedido.SerializeToString,
                response_deserializer=Cart__pb2.Response.FromString,
                )
        self.RemoveFromCart = channel.unary_unary(
                '/Cart/RemoveFromCart',
                request_serializer=Cart__pb2.PedidoId.SerializeToString,
                response_deserializer=Cart__pb2.Response.FromString,
                )
        self.ViewCart = channel.unary_unary(
                '/Cart/ViewCart',
                request_serializer=Cart__pb2.Nada.SerializeToString,
                response_deserializer=Cart__pb2.Response.FromString,
                )
        self.ViewProductInCart = channel.unary_unary(
                '/Cart/ViewProductInCart',
                request_serializer=Cart__pb2.ProductoId.SerializeToString,
                response_deserializer=Cart__pb2.Response.FromString,
                )
        self.AddQuantity = channel.unary_unary(
                '/Cart/AddQuantity',
                request_serializer=Cart__pb2.PedidoId.SerializeToString,
                response_deserializer=Cart__pb2.Response.FromString,
                )
        self.GetCarLength = channel.unary_unary(
                '/Cart/GetCarLength',
                request_serializer=Cart__pb2.Nada.SerializeToString,
                response_deserializer=Cart__pb2.Length.FromString,
                )
        self.GetPrecio = channel.unary_unary(
                '/Cart/GetPrecio',
                request_serializer=Cart__pb2.PedidoId.SerializeToString,
                response_deserializer=Cart__pb2.Precio.FromString,
                )


class CartServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewProductInCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddQuantity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarLength(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrecio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CartServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=Cart__pb2.Pedido.FromString,
                    response_serializer=Cart__pb2.Response.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=Cart__pb2.PedidoId.FromString,
                    response_serializer=Cart__pb2.Response.SerializeToString,
            ),
            'ViewCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewCart,
                    request_deserializer=Cart__pb2.Nada.FromString,
                    response_serializer=Cart__pb2.Response.SerializeToString,
            ),
            'ViewProductInCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewProductInCart,
                    request_deserializer=Cart__pb2.ProductoId.FromString,
                    response_serializer=Cart__pb2.Response.SerializeToString,
            ),
            'AddQuantity': grpc.unary_unary_rpc_method_handler(
                    servicer.AddQuantity,
                    request_deserializer=Cart__pb2.PedidoId.FromString,
                    response_serializer=Cart__pb2.Response.SerializeToString,
            ),
            'GetCarLength': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarLength,
                    request_deserializer=Cart__pb2.Nada.FromString,
                    response_serializer=Cart__pb2.Length.SerializeToString,
            ),
            'GetPrecio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrecio,
                    request_deserializer=Cart__pb2.PedidoId.FromString,
                    response_serializer=Cart__pb2.Precio.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Cart', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cart(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cart/AddToCart',
            Cart__pb2.Pedido.SerializeToString,
            Cart__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cart/RemoveFromCart',
            Cart__pb2.PedidoId.SerializeToString,
            Cart__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cart/ViewCart',
            Cart__pb2.Nada.SerializeToString,
            Cart__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewProductInCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cart/ViewProductInCart',
            Cart__pb2.ProductoId.SerializeToString,
            Cart__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddQuantity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cart/AddQuantity',
            Cart__pb2.PedidoId.SerializeToString,
            Cart__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCarLength(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cart/GetCarLength',
            Cart__pb2.Nada.SerializeToString,
            Cart__pb2.Length.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPrecio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cart/GetPrecio',
            Cart__pb2.PedidoId.SerializeToString,
            Cart__pb2.Precio.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
