# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Payment_pb2 as Payment__pb2


class PaymentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PagarTodoCarro = channel.unary_unary(
                '/Payment/PagarTodoCarro',
                request_serializer=Payment__pb2.None.SerializeToString,
                response_deserializer=Payment__pb2.Respuesta.FromString,
                )
        self.PagarItemEnElCarro = channel.unary_unary(
                '/Payment/PagarItemEnElCarro',
                request_serializer=Payment__pb2.ItemId.SerializeToString,
                response_deserializer=Payment__pb2.Respuesta.FromString,
                )


class PaymentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PagarTodoCarro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PagarItemEnElCarro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PagarTodoCarro': grpc.unary_unary_rpc_method_handler(
                    servicer.PagarTodoCarro,
                    request_deserializer=Payment__pb2.None.FromString,
                    response_serializer=Payment__pb2.Respuesta.SerializeToString,
            ),
            'PagarItemEnElCarro': grpc.unary_unary_rpc_method_handler(
                    servicer.PagarItemEnElCarro,
                    request_deserializer=Payment__pb2.ItemId.FromString,
                    response_serializer=Payment__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Payment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Payment(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PagarTodoCarro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Payment/PagarTodoCarro',
            Payment__pb2.None.SerializeToString,
            Payment__pb2.Respuesta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PagarItemEnElCarro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Payment/PagarItemEnElCarro',
            Payment__pb2.ItemId.SerializeToString,
            Payment__pb2.Respuesta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
